import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "antd";
import Router from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = Router;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flexed-column">
        <h1>Welcome to Pickey</h1>
        {/* <Button className="btn" type="primary"
          onClick={() => {
            router.push("/stage1");
          }}
        >
          Start
        </Button> */}
        <button
          className="btn"
          onClick={() => {
            router.push("/stage1");
          }}
        >
          Start
        </button>
      </main>
    </>
  );
}
